In [4]:
import pandas as pd

In [5]:
df=pd.read_excel('D:\\Machine-Learning-Practice\\My-Learning-Projects\\data2.xlsx')

In [6]:
df

,Rank,Company,Sales($billion),Profits($billion),Assets,Market Value,Country
0,40,Commonwealth Bank,47.8,7.3,735.2,117.5,Australia
1,44,BHP Billiton,72.2,15.4,129.3,184.7,Australia
2,48,Westpac Banking Group,43.9,6.2,699.6,98.9,Australia
3,58,National Australian Bank,49.2,4.2,791.3,76.3,Australia
4,66,ANZ,37.5,5.9,666.9,81.2,Australia
5,168,Wesfarmers,59.0,2.2,42.9,51.9,Australia
6,200,Telstra,25.8,3.5,40.5,58.4,Australia
7,271,Woolworths,56.4,1.9,21.5,46.3,Australia
8,373,AMP,17.2,0.7,122.1,16.0,Australia
9,393,Suncorp Group,15.6,0.7,98.3,15.9,Australia
10,411,QBE Insurance Group,17.0,0.8,50.8,17.0,Australia
11,445,Macquarie Group,11.4,0.8,157.8,13.5,Australia
12,483,Woodside Petroleum,6.4,3.0,23.9,31.9,Australia
13,494,Origin Energy,13.2,1.0,28.7,14.9,Australia
14,630,Westfield Group,2.5,1.8,35.3,25.4,Australia
15,703,Fortescue Metals Group,7.0,1.6,14.9,13.2,Australia
16,744,Newcrest Mining,4.5,1.1,20.8,17.5,Australia
17,875,Amcor,12.5,0.4,11.5,11.9,Australia
18,952,Insurance Australia Group,9.2,0.2,25.4,12.4,Australia
19,956,CSL,4.5,1.0,5.8,32.0,Australia
20,1014,Santos,3.4,0.5,17.7,13.1,Australia
21,1016,Land Lease Group,11.9,0.5,12.6,5.8,Australia
22,1067,Westfield Retail Trust,0.5,0.9,13.8,9.8,Australia
23,1116,Brambles,5.6,0.6,7.7,14.1,Australia
24,1219,Stockland Australia,2.1,0.5,14.9,8.8,Australia
25,1242,AGL Energy,7.6,0.1,14.5,9.5,Australia
26,1249,Coca-Cola Amatil,5.3,0.5,7.0,12.1,Australia
27,1254,Qantas Airways,16.1,-0.3,21.7,4.1,Australia
28,1256,Orica,6.9,0.4,7.7,9.6,Australia